name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        
      - name: Install stable toolchain
        uses: actions-rs/toolchain
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo
        continue-on-error: true  # WARNING: only for this example, remove it!
        with:
          command: check
        
